baseURL = "https://jeju202007.dglee.kr/"
languageCode = "en-us"
theme = "hugo-theme-tokiwa"
title = "Jeju 2020 07 01 - 2020 07 07"

[params]
    mainpagetitle = "2020. 07 제주 여행의 기록."
    mainpagesubtitle = "우중 솔로 제주 여행"
    mainpagedesc = "이달들어... 마음이 혼란스럽고.. 너무 힘든 탓에.. 한라산이나 올라가보기로 하고는.. 그저께 티켓팅 함."
    copyrightname = "DG"
